# Generated by Django 5.0.6 on 2024-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calories', models.CharField(max_length=35)),
                ('fats', models.CharField(max_length=35)),
                ('carbs', models.CharField(max_length=35)),
                ('protein', models.CharField(max_length=35)),
                ('unsaturated_fats', models.CharField(max_length=35)),
                ('sugar', models.CharField(max_length=35)),
                ('salt', models.CharField(max_length=35)),
                ('portion', models.CharField(max_length=35)),
            ],
        ),
    ]
