# Generated by Django 5.0.6 on 2024-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='protein',
            new_name='proteins',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='salt',
            new_name='salts',
        ),
    ]
